version: "3"
    
tasks:
    run: 
        desc: Run the app
        dir: 'server' 
        cmds:
          - task: clean
          - task: build-webapp
          - GOFLAGS=-mod=mod go run main.go

    build-go:
        internal: true
        dir: 'server' 
        cmds:
            - GOFLAGS=-mod=mod go build -o ../bin/SingStarSwap.exe main.go

    build-webapp:
        dir: 'webapp'
        cmds:
          - ng build

    build:
        desc: Build the app
        cmds:
          - task: clean
          - task: build-webapp
          - task: build-go

    clean:
        desc: Clean the distribution dirs
        cmds:
        - rm -rf server/static/*
        - rm -rf dist
        - rm -rf bin

    # generate:
    #     desc: Generate image to ascii files
    #     cmds:
    #     - TODO